import Head from "next/head";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Layout from "@/components/layout/Layout";
import MainBanner from "@/components/home/main-banner/mainBanner";
import AboutSummary from "@/components/home/about-summary/AboutSummary";
import ServiceList from "@/components/home/services-list/ServiceList";
import ProductSummary from "@/components/general/product-summary/ProductSummary";
import MaterialSummary from "@/components/home/material-summary/MaterialSummary";
import CallToAction from "@/components/general/call-to-action/CallToAction";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Dananz Interior Design</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <MainBanner />
        <AboutSummary />
        <ServiceList />
        <ProductSummary />
        <MaterialSummary />
        <CallToAction />
      </Layout>
    </>
  );
}
